spring:
  cloud:
    function:
      definition: userConsumer;cryptocurrencyConsumer
    stream:
      bindings:
        userConsumer-in-0:
          destination: topic1
        cryptocurrencyConsumer-in-0:
          destination: topic2
      binder:
        brokers: localhost:9092
