spring:
  cloud:
    function:
      definition: userConsumer;cryptocurrencyConsumer
    stream:
      bindings:
        userConsumer-in-0:
          destination: userTopic
        cryptocurrencyConsumer-in-0:
          destination: cryptocurrencyTopic,cryptocurrencyTopic2
      binder:
        brokers: localhost:9092
